### ISSUE TITLE
Policy owner definition - core specification

### ISSUE THREAD

**Issue by midwave** [hexa-org/policy#14]
There is no reference in a policy definition for the owner of a policy.  It's not clear to me in the schema how that would be defined, and yet this is a core capability of any policy engine.  

In thinking about this from a migration perspective, one would need to export the definition somehow from the source system.  If the response is that ownership of a policy is a policy itself, there should still be a way to reference the policy container.  

I suggest making a condition of the policy exist for ownership as well as execution of the policy.  

If this is considered in the specification, then an example would be valuable.

**Comment by independentid** [comment]
Not sure what you mean by owner. Do you mean administrative owner or the policy binding, or app?

There is additional context  held in the policy orchestrator which loads policy via the admin APIs of the platforms. 

In policy, administrative meta info (layer/component/app etc) is in the meta object.

**Comment by midwave** [comment]
I mean the administrative owner of the policy.  Thanks for the pointer to the meta object.

**Comment by midwave** [comment]
OK, I reviewed [https://raw.githubusercontent.com/idql-org/IDQL-specs/main/schema/idql-policy.schema.json](url) and did not identify a policy owner attribute in its definition.  When building a security policy, there is always an administrative owner of the policy with privileged access.  The owner can be defined as a list of users, a security group, or some other definition.  Essentially, the owner of a policy can have a self-referencing definition policy itself.  Likewise, there should also be a way to promote ownership of a policy in out-of-office situations.  These capabilities are defined in legacy ICAM products, and it's not clear to me that these privileged account situations are captured by the standard.

**Comment by independentid** [comment]
This will likely depend on how we handle policy lifecycle outside of platforms. The current code base just shows and allow manipulation of deployed policy. Because of this, there is almost no ability to add meta information like administrative owner. 

I believe we need a central state of authority (eg GIT) where orchestrator deploys and maps from. It also enables compliance checks etc. 

Phil

**Comment by independentid** [comment]
I am going to close this. At this point the hexa project doesn't store policy outside of the platforms and the "owner" is usually dictated by the platform API.  It may be useful to have an administrative owner meta data item if policy is managed externally and then provisioned CI/CD systems.
